import { InventoryItem, CompanyProfile } from "./types";

export const CATEGORIES = [
  "Furniture",
  "Appliance",
  "Electronics",
  "Box",
  "Decor",
  "Misc"
];

export const ITEM_TAGS = [
  "Fragile",
  "Heavy",
  "Valuable",
  "Stackable",
  "Glass",
  "Hazardous"
];

export const FORBIDDEN_KEYWORDS = [
    "book", "magazine", "paper", "file", "folder", "envelope", "dvd", "cd", "game case",
    "cloth", "shirt", "pant", "shoe", "boot", "sneaker", "jacket", "coat", "hat", "glove", "sock", "underwear", "laundry", "towel", "linen", "pillow", "cushion", "blanket", "comforter",
    "dish", "plate", "bowl", "cup", "glass", "mug", "utensil", "fork", "spoon", "knife", "cutlery", "pot", "pan", "skillet", "tray", "tupperware", "container", "bottle", "jar", "can", "food", "spice", "condiment",
    "kettle", "waffle", "hair dryer", "curling iron", "hand blender",
    "toiletry", "soap", "shampoo", "lotion", "brush", "makeup", "perfume", "medicine", "toothbrush", "toothpaste",
    "remote", "controller", "cable", "charger", "cord", "mouse", "keyboard", "headphone", "earbud", "router", "modem",
    "toy", "doll", "lego", "figurine", "vase", "picture frame", "photo", "candle", "plant", "flower", "waste basket", "trash can", "garbage", "bin"
];

// Mapped exactly from user provided list (Cleaned Version)
export const REFERENCE_ITEM_DATA: Record<string, { volume: number, weight: number }> = {
  "AC, Large": { volume: 20, weight: 140 },
  "AC, Small/Window": { volume: 10, weight: 70 },
  "Air Compressor": { volume: 5, weight: 35 },
  "Air Hockey Table": { volume: 40, weight: 280 },
  "All-in-One Gym, Large": { volume: 100, weight: 700 },
  "All-in-One Gym, Medium": { volume: 50, weight: 350 },
  "Armchair": { volume: 10, weight: 70 },
  "Baby Crib": { volume: 10, weight: 70 },
  "Bar, Portable": { volume: 15, weight: 105 },
  "Barstool": { volume: 5, weight: 35 },
  "Bassinet": { volume: 5, weight: 35 },
  "Bassinet & Stand": { volume: 10, weight: 70 },
  "BBQ Grill": { volume: 25, weight: 175 },
  "Basketball Hoop": { volume: 50, weight: 350 },
  "Bed, Bunk (Set of 2)": { volume: 60, weight: 420 },
  "Bed, Day": { volume: 30, weight: 210 },
  "Bed, Double": { volume: 60, weight: 420 },
  "Bed, King": { volume: 70, weight: 490 },
  "Bed, Queen": { volume: 65, weight: 455 },
  "Bed, Rollaway": { volume: 10, weight: 70 },
  "Bed, Single": { volume: 40, weight: 280 },
  "Bed, Waterbed Base": { volume: 15, weight: 105 },
  "Bed, Youth": { volume: 30, weight: 210 },
  "Bench, Harvest": { volume: 10, weight: 70 },
  "Bench, Piano": { volume: 5, weight: 35 },
  "Bicycle": { volume: 10, weight: 70 },
  "Bird Bath": { volume: 5, weight: 35 },
  "Birdcage": { volume: 4, weight: 28 },
  "Bookcase, Large": { volume: 30, weight: 210 },
  "Bookcase, Medium": { volume: 20, weight: 140 },
  "Bookcase, Sectional": { volume: 5, weight: 35 },
  "Bookcase, Small": { volume: 10, weight: 70 },
  "Bookshelves, Large": { volume: 30, weight: 210 },
  "Bookshelves, Medium": { volume: 20, weight: 140 },
  "Bookshelves, Sectional": { volume: 5, weight: 35 },
  "Bookshelves, Small": { volume: 15, weight: 105 },
  "Box, Dish Pack": { volume: 9, weight: 63 },
  "Box, Extra Large": { volume: 6, weight: 42 },
  "Box, Large": { volume: 4.5, weight: 31.5 },
  "Box, Medium": { volume: 3, weight: 21 },
  "Box, Mirror/Picture": { volume: 5, weight: 35 },
  "Box, Small": { volume: 1.5, weight: 10.5 },
  "Box, Tote": { volume: 6, weight: 42 },
  "Box, Wardrobe": { volume: 12, weight: 84 },
  "Cabinet, China": { volume: 50, weight: 350 },
  "Cabinet, Corner": { volume: 20, weight: 140 },
  "Cabinet, Curio": { volume: 10, weight: 70 },
  "Cabinet, Utility": { volume: 40, weight: 280 },
  "Canoe": { volume: 20, weight: 140 },
  "Card Table": { volume: 5, weight: 35 },
  "Cedar Chest": { volume: 15, weight: 105 },
  "Chair, Aluminum": { volume: 1, weight: 7 },
  "Chair, Arm": { volume: 10, weight: 70 },
  "Chair, Arm/Desk": { volume: 5, weight: 35 },
  "Chair, Boudoir": { volume: 10, weight: 70 },
  "Chair, Breakfast": { volume: 5, weight: 35 },
  "Chair, Child": { volume: 4, weight: 28 },
  "Chair, Dining": { volume: 5, weight: 35 },
  "Chair, Folding": { volume: 2, weight: 14 },
  "Chair, Glider": { volume: 15, weight: 105 },
  "Chair, High": { volume: 5, weight: 35 },
  "Chair, Lawn": { volume: 5, weight: 35 },
  "Chair, Lounge": { volume: 25, weight: 175 },
  "Chair, Occasional": { volume: 15, weight: 105 },
  "Chair, Overstuffed": { volume: 25, weight: 175 },
  "Chair, Overstuffed, Medium": { volume: 20, weight: 140 },
  "Chair, Overstuffed, Small": { volume: 10, weight: 70 },
  "Chair, Porch": { volume: 10, weight: 70 },
  "Chair, Rocker": { volume: 12, weight: 84 },
  "Chair, Rocking": { volume: 15, weight: 105 },
  "Chair, Small": { volume: 10, weight: 70 },
  "Chair, Straight": { volume: 5, weight: 35 },
  "Chair, Wicker/Metal": { volume: 5, weight: 35 },
  "Chair, Wing Back": { volume: 10, weight: 70 },
  "Chest, Armoire": { volume: 50, weight: 350 },
  "Chest, Small": { volume: 25, weight: 175 },
  "Chest, Toy": { volume: 10, weight: 70 },
  "China Buffet Base": { volume: 40, weight: 280 },
  "China Hutch": { volume: 20, weight: 140 },
  "Christmas Tree/Decoration": { volume: 3, weight: 21 },
  "Coffee Table": { volume: 10, weight: 70 },
  "Computer/Monitor/Accessories": { volume: 15, weight: 105 },
  "Cooler": { volume: 2, weight: 14 },
  "Cot, Folding": { volume: 10, weight: 70 },
  "Credenza": { volume: 10, weight: 70 },
  "Crib": { volume: 10, weight: 70 },
  "Deep Freezer": { volume: 30, weight: 210 },
  "Dehumidifier": { volume: 10, weight: 70 },
  "Desk, Executive": { volume: 50, weight: 350 },
  "Desk, Office": { volume: 10, weight: 70 },
  "Desk, Return": { volume: 8, weight: 56 },
  "Desk, Secretary": { volume: 22, weight: 154 },
  "Desk, Small/Winthrop": { volume: 22, weight: 154 },
  "Dishwasher": { volume: 20, weight: 140 },
  "Dresser, Bureau (3 Drawer)": { volume: 35, weight: 245 },
  "Dresser, Double": { volume: 40, weight: 280 },
  "Dresser, Large (6 Drawer)": { volume: 50, weight: 350 },
  "Dresser, Single": { volume: 20, weight: 140 },
  "Dresser, Small/Tallboy": { volume: 25, weight: 175 },
  "Dresser, Triple": { volume: 50, weight: 350 },
  "Dryer, Electric": { volume: 25, weight: 175 },
  "Dryer, Gas": { volume: 25, weight: 175 },
  "Eliptical": { volume: 25, weight: 175 },
  "Entertainment Unit": { volume: 35, weight: 245 },
  "Entertainment Unit, Large": { volume: 50, weight: 350 },
  "Exercise Bike": { volume: 15, weight: 105 },
  "Fan": { volume: 5, weight: 35 },
  "Filing Cabinet, 2 Drawer": { volume: 5, weight: 35 },
  "Filing Cabinet, 3 Drawer": { volume: 8, weight: 56 },
  "Filing Cabinet, 4 Drawer": { volume: 10, weight: 70 },
  "Fireplace Tools": { volume: 5, weight: 35 },
  "Futon": { volume: 42, weight: 294 },
  "Grandfather Clock": { volume: 15, weight: 105 },
  "Guitar/Keyboard": { volume: 5, weight: 35 },
  "Hamper/Basket": { volume: 3, weight: 21 },
  "Heater, Gas/Electric": { volume: 5, weight: 35 },
  "Ironing Board": { volume: 1, weight: 7 },
  "Ladder, 6 ft": { volume: 4, weight: 28 },
  "Ladder, 8 ft": { volume: 6, weight: 42 },
  "Ladder, Extension": { volume: 15, weight: 105 },
  "Lamp, Floor": { volume: 3, weight: 21 },
  "Lamp, Pole": { volume: 3, weight: 21 },
  "Lamp, Table": { volume: 1, weight: 7 },
  "Lawn Mower, Power": { volume: 10, weight: 70 },
  "Lawn Mower, Riding": { volume: 50, weight: 350 },
  "Lawn Mower, Roller": { volume: 5, weight: 35 },
  "Microwave": { volume: 5, weight: 35 },
  "Mirror": { volume: 5, weight: 35 },
  "Nightstand": { volume: 5, weight: 35 },
  "Ottoman": { volume: 5, weight: 35 },
  "Painting": { volume: 3, weight: 21 },
  "Piano, Baby Grand": { volume: 70, weight: 490 },
  "Piano, Grand/Concert": { volume: 80, weight: 560 },
  "Piano, Organ/Console": { volume: 60, weight: 420 },
  "Piano, Spinet": { volume: 50, weight: 350 },
  "Ping Pong Table": { volume: 30, weight: 210 },
  "Pool Table": { volume: 60, weight: 420 },
  "Refrigerator, 6 cu ft or Less": { volume: 10, weight: 70 },
  "Refrigerator, 11–15 cu ft": { volume: 45, weight: 315 },
  "Refrigerator, 11+ cu ft (No Ice)": { volume: 60, weight: 420 },
  "Refrigerator, 11+ cu ft (With Ice)": { volume: 60, weight: 420 },
  "Refrigerator, Small": { volume: 20, weight: 140 },
  "Rug, Large": { volume: 10, weight: 70 },
  "Rug, Small": { volume: 3, weight: 21 },
  "Safe, Large": { volume: 20, weight: 140 },
  "Safe, Medium": { volume: 15, weight: 105 },
  "Safe, Small": { volume: 10, weight: 70 },
  "Sewing Machine, Cabinet": { volume: 20, weight: 140 },
  "Sewing Machine, Console": { volume: 10, weight: 70 },
  "Sewing Machine, Portable": { volume: 10, weight: 70 },
  "Sofa, 2 Cushion": { volume: 35, weight: 245 },
  "Sofa, 3 Cushion": { volume: 50, weight: 350 },
  "Sofa, 4 Cushion/Hide": { volume: 60, weight: 420 },
  "Sofa, Chaise": { volume: 15, weight: 105 },
  "Sofa, Loveseat": { volume: 35, weight: 245 },
  "Sofa, Recliner": { volume: 25, weight: 175 },
  "Sofa, Sectional": { volume: 100, weight: 700 },
  "Sofa, Sectional (Per Section)": { volume: 25, weight: 175 },
  "Sofa, Settee": { volume: 15, weight: 105 },
  "Stool": { volume: 4, weight: 28 },
  "Table, Coffee": { volume: 10, weight: 70 },
  "Table, Dining": { volume: 30, weight: 210 },
  "Table, Drop/Occasional": { volume: 12, weight: 84 },
  "Table, Side": { volume: 5, weight: 35 },
  "Table, Utility": { volume: 5, weight: 35 },
  "TV, Flat Screen": { volume: 9, weight: 63 },
  "TV, LCD (Mounted)": { volume: 12, weight: 84 },
  "TV, LCD (On Stand)": { volume: 12, weight: 84 },
  "TV, Plasma": { volume: 15, weight: 105 },
  "TV, Small Table Model": { volume: 5, weight: 35 },
  "TV, Console": { volume: 20, weight: 140 },
  "Vacuum Cleaner": { volume: 3, weight: 21 },
  "Washer, Front Load": { volume: 25, weight: 175 },
  "Washer, Top Load": { volume: 25, weight: 175 },
  "Wheelbarrow": { volume: 10, weight: 70 },
  "Wine Rack": { volume: 3, weight: 21 },
  "Workbench": { volume: 20, weight: 140 },
  "Workbench, Large": { volume: 50, weight: 350 }
};

export const STANDARD_MOVING_ITEMS = Object.keys(REFERENCE_ITEM_DATA).sort();

export const INITIAL_INVENTORY: InventoryItem[] = [];

export const DEFAULT_ADMIN_EMAIL = "dispatch@movemate.ai";

// --- Multi-Tenant Data ---

export const SUPER_ADMIN_CREDS = {
  username: "",
  password: ""
};

export const INITIAL_COMPANIES: CompanyProfile[] = [];
