// src/services/emailService.ts
import { supabase } from './supabaseClient';
import { InventoryItem, JobDetails } from '../types';

export const emailService = {
  /**
   * Sends the inventory email using the Supabase Edge Function "send-estimate-email".
   * The Edge Function calls Resend under the hood.
   */
  async sendInventoryEmail(
    tenantAdminEmail: string,
    jobDetails: JobDetails,
    items: InventoryItem[]
  ): Promise<boolean> {
    // 1. Calculate Totals
    const selectedItems = items.filter(i => i.selected);
    const totalVolume = selectedItems.reduce(
      (acc, item) => acc + item.volumeCuFt * item.quantity,
      0
    );
    const totalWeight = selectedItems.reduce(
      (acc, item) => acc + item.weightLbs * item.quantity,
      0
    );

    // 2. Format Items List
    const formattedList = selectedItems
      .map(item => {
        return `- ${item.quantity} x ${item.name} (Vol: ${
          item.volumeCuFt * item.quantity
        } cf, Wt: ${item.weightLbs * item.quantity} lbs)`;
      })
      .join('\n');

    // 3. Format Packing Materials
    let packingText = 'None';
    const reqs = jobDetails.packingReqs;
    if (reqs) {
      const materials: string[] = [];
      if (reqs.tvBox && reqs.tvBox > 0) {
        materials.push(`  - TV Boxes: ${reqs.tvBox}`);
      }
      if (reqs.wardrobeBox && reqs.wardrobeBox > 0) {
        materials.push(`  - Wardrobe Boxes: ${reqs.wardrobeBox}`);
      }
      if (reqs.mirrorBox && reqs.mirrorBox > 0) {
        materials.push(`  - Mirror Boxes: ${reqs.mirrorBox}`);
      }
      if (reqs.mattressCover && reqs.mattressCover > 0) {
        materials.push(`  - Mattress Covers: ${reqs.mattressCover}`);
      }

      if (materials.length > 0) {
        packingText = materials.join('\n');
      }

      if (reqs.generalNotes) {
        packingText += `\n\n  Notes\n  ${reqs.generalNotes}`;
      }
    }

    // 4. Construct Email Body
    let header = '';
    if (jobDetails.jobId) {
      header = `Job ID: ${jobDetails.jobId}`;
    } else {
      header = `${jobDetails.customerName ?? 'Unknown Customer'} - ${
        jobDetails.moveDate ?? 'Unknown Date'
      }`;
    }

    // Company identifier for Gmail filters / forwarding
    const companyName = jobDetails.companyName || 'Unknown Company';

    const emailBody = `
COMPANY_NAME: ${companyName}

=========================================
NEW INVENTORY ESTIMATE SUBMISSION
=========================================

${header}

SUMMARY STATISTICS
-----------------------------------------
Total Items:  ${selectedItems.reduce((acc, i) => acc + i.quantity, 0)}
Total Volume: ${Math.round(totalVolume)} cu ft
Total Weight: ${Math.round(totalWeight)} lbs

INVENTORY LIST
-----------------------------------------
${formattedList}

PACKING REQUIREMENTS
-----------------------------------------
${packingText}

-----------------------------------------
Generated by MoveMate AI
`;

    const subject = `Inventory Estimate - ${header}`;

    // Resend sandbox: always send to this Gmail inbox
    const toEmail = 'whisperwindworkspace@gmail.com';

    console.log('Sending email to:', toEmail);

    const { error } = await supabase.functions.invoke('send-estimate-email', {
      body: {
        to: toEmail,
        subject,
        body: emailBody,
      },
    });

    if (error) {
      console.error('Email send error', error);
      throw error;
    }

    return true;
  },
};
